In [4]:
#Question-1
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
print("Type of Age:",type(ages))
ages.sort()
print("Sorted List of ages is:" ,ages)
#Program to find min and max for the variable age
print("Minimum age count is:" ,min(ages))
ages.append(min(ages))
print(ages)
ages.append(max(ages))
print(ages)
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
#sorting the list to find the Median
ages.sort()
print(ages)
# printing list
print("The Sorted List is : " + str(ages))
# Median of the provided list is Given Below
# Using loop + "~" operator
midValue = len(ages) // 2
result = (ages[midValue] + ages[~midValue]) / 2
# Printing result
print("Median of list is : " + str(result))
print(sum(ages))
print("Average of the list is :" ,sum(ages)/len(ages))#Average Of the List
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
ages.sort()
print(ages)
print("Minimum Value is :",ages[0])#Minimum value
print("Maximam Value is:",ages[9])#Maximum value
Range = ages[9]-ages[0]
print("Range of the List is :",Range)

Type of Age: <class 'list'>
Sorted List of ages is: [19, 19, 20, 22, 24, 24, 24, 25, 25, 26]
Minimum age count is: 19
[19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 19]
[19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 19, 26]
[19, 19, 20, 22, 24, 24, 24, 25, 25, 26]
The Sorted List is : [19, 19, 20, 22, 24, 24, 24, 25, 25, 26]
Median of list is : 24.0
228
Average of the list is : 22.8
[19, 19, 20, 22, 24, 24, 24, 25, 25, 26]
Minimum Value is : 19
Maximam Value is: 26
Range of the List is : 7


In [2]:
#Question -2

#Empty Dictionary
dog={}
print("Type of Dog Variable is:", type(dog))
dog.update({'name':'Adisi','color':'Brown','Breed':'Labrador','legs':'short','age':4})#Here I have used update() to add values into the Dictionary
print("Items in the Dog Dictionary are:" ,dog)
print("The name of the dog is:" ,dog['name'])
#skills=[]
MyDict={'first_name':'Aditya Sai Varma', 'last_name':'Saripalli' , 'gender':'Male', 'age':21, 'martial status':"Single", 'skills':['c','Python','Java','SQL'],'country':'USA', 'city': 'Overland Park', 'address':'8601 W 131st Ter Overland Prk Kansas 66213'}
print(MyDict)
print("My First name present in the Dictionary is:" ,MyDict['first_name'])
print("The Lenght of the Student Dictionary is :", len(MyDict))
print("The Items present in Skills are:" ,MyDict['skills'])
S = MyDict['skills']
print(type(S))
MyDict={'first_name':'Aditya Sai Varma', 'last_name':'Saripalli' , 'gender':'Male', 'age':21, 'martial status':"Single", 'skills':['c','Python','Java','SQL'],'country':'USA', 'city': 'Overland Park', 'address':'8601 W 131st Ter Overland Prk Kansas 66213'}
MyDict['skills'].append('AWS')#This is the First value which is added to the list
MyDict['skills'].append('Java-Script')#This is the Second one 
print("The Total no of values along with Added values in the List named skills are:",MyDict['skills'])
MyDict={'first_name':'Aditya Sai Varma', 'last_name':'Saripalli' , 'gender':'Male', 'age':21, 'martial status':"Single", 'skills':['c','Python','Java','SQL'],'country':'USA', 'city': 'Overland Park', 'address':'8601 W 131st Ter Overland Prk Kansas 66213'}
print(list(MyDict))#This shows and prints MyDict Values in the form of List.
print(list(MyDict.keys()))#Here we are accesing keys from MyDict in the form of list by converting it into list
print(list(MyDict.values()))#Here we have got Dictionary values as a list by converting dict to list
#Here we have typecasted form Dict to List



Type of Dog Variable is: <class 'dict'>
Items in the Dog Dictionary are: {'name': 'Adisi', 'color': 'Brown', 'Breed': 'Labrador', 'legs': 'short', 'age': 4}
The name of the dog is: Adisi
{'first_name': 'Aditya Sai Varma', 'last_name': 'Saripalli', 'gender': 'Male', 'age': 21, 'martial status': 'Single', 'skills': ['c', 'Python', 'Java', 'SQL'], 'country': 'USA', 'city': 'Overland Park', 'address': '8601 W 131st Ter Overland Prk Kansas 66213'}
My First name present in the Dictionary is: Aditya Sai Varma
The Lenght of the Student Dictionary is : 9
The Items present in Skills are: ['c', 'Python', 'Java', 'SQL']
<class 'list'>
The Total no of values along with Added values in the List named skills are: ['c', 'Python', 'Java', 'SQL', 'AWS', 'Java-Script']
['first_name', 'last_name', 'gender', 'age', 'martial status', 'skills', 'country', 'city', 'address']
['first_name', 'last_name', 'gender', 'age', 'martial status', 'skills', 'country', 'city', 'address']
['Aditya Sai Varma', 'Saripalli',

In [50]:
#Question-3

MySisters=('Mahitha','Suma','JayaSree')
print(type(MySisters))
print("The People in the Tuple(MySisters) are :",MySisters)
MyBrothers=("Hemanth","Vikranth","Chaitanya")
print("The People in the Tuple(MyBrothers) are:",MyBrothers)
sibilings = MySisters+MyBrothers
print("On a Whole my Sibilings are :",sibilings)
print("Lenght of the tuple named sibilings is :",len(sibilings))
MyParentNames=("Mohan Venkata Siva Rama Raju","Rupa Devi")
print("The Name of my parents are :",MyParentNames)
family_members=sibilings+MyParentNames
print("The names of my Family members are:",family_members)


<class 'tuple'>
The People in the Tuple(MySisters) are : ('Mahitha', 'Suma', 'JayaSree')
The People in the Tuple(MyBrothers) are: ('Hemanth', 'Vikranth', 'Chaitanya')
On a Whole my Sibilings are : ('Mahitha', 'Suma', 'JayaSree', 'Hemanth', 'Vikranth', 'Chaitanya')
Lenght of the tuple named sibilings is : 6
The Name of my parents are : ('Mohan Venkata Siva Rama Raju', 'Rupa Devi')
The names of my Family members are: ('Mahitha', 'Suma', 'JayaSree', 'Hemanth', 'Vikranth', 'Chaitanya', 'Mohan Venkata Siva Rama Raju', 'Rupa Devi')


In [10]:
#Question-4

it_companies = {'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'}
print("Lenght of it_companies are:" ,len(it_companies))
it_companies.add("Twitter")
print("It Companies with Updation of one comapny addition is:",it_companies)#Here in Set while adding the items in it, it randomly allocates its place anywhere in the set
it_companies.update(["DBS","NCR","TCS","Infosys"])#Here in Set as add() only supports only one argument we woiuld be using update() to add multiple items
print("Names of the Multiple Company names which are added to the Original One are :",it_companies)
it_companies.remove("Twitter")#Here for removing a particualr element we would be using remove() ,to remove a random element we would be using pop() method
#it_companies.remove("TOSLO")#The expalnation for this is explained clearly in the word document
#it_companies.remove("TOSLO")
A = {19, 22, 24, 20, 25, 26}
B = {19, 22, 20, 25, 26, 24, 28, 27}
Res=A.union(B)
print("Joining the sets of A and will be :",Res)#Here Union Combines all the elements in the two sets which doesnt include the duplicates in both of the sets
Res1=A.intersection(B)
print("Intersection of the sets A and B is :",Res1)#It returns the common items present in the two sets
print("Finding Whether A is Subset of B? (T/F):",A.issubset(B))#Here as all the elements in  A are in B we can say that A is Subset of B,if it isnt true then issubset() return false basically it returns Boolean Values based on the Context
print("Finding Whether A and B are Disjoint sets or not?",A.isdisjoint(B))#Here it is false because there are similar items that are present in the both of the sets.The main Criteria for Disjoint Sets is that it shouldn't have common items present.
print("The Symmetric difference between the two sets A And are:",B.symmetric_difference(A))
#It Basically caluculates{(A\B)∪(B\A)} to find Symmetric Difference
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
print(type(ages))
print(set(ages))#Converting List ages[] to Set
#print(type(ages))#List Converted to set.
#Inserting items of  Set B into Set A
A.update(B)
print("After Inserting Items of B into A :",A)
B.update(A)
print("After Inserting Items of A into B :",B)
#Below is the code for comparing the lenght for both list and set.
if len(set(ages))==len(A):
    print("Both the set and List are having same no of items i.e Lenght")
else:
    print("The Lenght of list and set are not same")
del A
print(A)#Error
del B
print(B)
#Here it has deleted the set which we have preferred so that the Python Virtual Machine cannot find the set that is present in the memory




Lenght of it_companies are: 7
It Companies with Updation of one comapny addition is: {'Google', 'Apple', 'Amazon', 'Microsoft', 'IBM', 'Twitter', 'Facebook', 'Oracle'}
Names of the Multiple Company names which are added to the Original One are : {'Google', 'Twitter', 'Infosys', 'TCS', 'Facebook', 'Apple', 'Oracle', 'Microsoft', 'IBM', 'Amazon', 'NCR', 'DBS'}
Joining the sets of A and will be : {19, 20, 22, 24, 25, 26, 27, 28}
Intersection of the sets A and B is : {19, 20, 22, 24, 25, 26}
Finding Whether A is Subset of B? (T/F): True
Finding Whether A and B are Disjoint sets or not? False
The Symmetric difference between the two sets A And are: {27, 28}
<class 'list'>
{19, 20, 22, 24, 25, 26}
After Inserting Items of B into A : {19, 20, 22, 24, 25, 26, 27, 28}
After Inserting Items of A into B : {19, 20, 22, 24, 25, 26, 27, 28}
The Lenght of list and set are not same


NameError: name 'A' is not defined

In [28]:
#Question-5

def AreaOfCircle(radius):
    _area_of_circle_= 3.14*radius*radius
    print("Area of Circle is:",_area_of_circle_)
def CircumferenceOfCircle(radius):
    _circum_of_circle_ = 2*3.14*radius
    return _circum_of_circle_ #Return the Circum Value
AreaOfCircle(30)
Circumference=CircumferenceOfCircle(30)#this holds the circumference value of the circle
print("The Circumference of the Circle  is:",Circumference)


Area of Circle is: 2826.0
The Circumference of the Circle  is: 188.4


In [1]:
Input_radius=int(input("Enter the radius for the Circle: "))#Here we are converting the string input to Integer by doing Type_Casting
def AreaOfCircle(radius):
    _area_of_circle_= 3.14*radius*radius
    print("Area of Circle is:",_area_of_circle_)
AreaOfCircle(Input_radius)

Enter the radius for the Circle: 30
Area of Circle is: 2826.0


In [73]:
#Question-6
#Unique Words in the list
Input = "I am a teacher and I love to inspire and teach people"
B = set(Input.split(" "))#Here at first it splits the string into different words and then it is converted into set where the duplicate value aren't allowed 
#Through this Process we can get Unique word from the given String
print("Unique Words from the List are :", B)


Unique Words from the List are : {'am', 'I', 'people', 'a', 'and', 'teacher', 'inspire', 'teach', 'to', 'love'}


In [1]:
#Question-7

#Using Tab Escape Sequence character
#Name Age Country City
 #Asabeneh 250 Finland Helsinki
print('Name\tAge\tCountry\tCity\nAsbeneh\t 250\t Finland Helsinki')

Name	Age	Country	City
Asbeneh	 250	 Finland Helsinki


In [33]:
#Question-8

radius = 10
area = 3.14 * radius ** 2#Here %d represents the integer that to be displayed
formated_string = "radius = %d\narea = 3.14*radius**%d\nThe area of circle with a radius %d is %d square meter." %(radius,2,radius,area)
print(formated_string)
#We can also use format() to display string which we want

radius = 10
area = 3.14*radius**2
The area of circle with a radius 10 is 314 square meter.


In [74]:
#Question-9
#L1: [150, 155, 145, 148](input)
#Output: [68.03, 70.3, 65.77, 67.13]
LBS = []#Empty List
S = int(input("Enter the List size for Conversion:"))#Taking Input from the User
for K in range(S):
    StudentWeights = int(input("Enter weights(lbs) of N students"))
    LBS.append(StudentWeights)#Appending the weigths into the LBS[]
KGS=[[]] * S
for K in range(S):
    KGS[K] = LBS[K]/2.205
print(KGS)
print(LBS)

Enter the List size for Conversion:4
Enter weights(lbs) of N students150
Enter weights(lbs) of N students155
Enter weights(lbs) of N students145
Enter weights(lbs) of N students148
[68.02721088435374, 70.29478458049887, 65.75963718820861, 67.12018140589569]
[150, 155, 145, 148]


In [10]:
#Question=10
import numpy as np

#We use sklearn which is a package where we acan find MAchine Learning Alogrithms
from sklearn.model_selection import train_test_split#here tran_test_split to split the data
from sklearn.neighbors import KNeighborsClassifier#Here we Use this to implement the KNN Algorithm
L = np.array([[1,0],[2,0],[3,0],[6,0],[6,0],[7,0],[10,0],[11,0]])#These are the data sets which are obtained from the given graph
M = np.array([0,0,1,1,1,0,0,0])#this represents the classes at individual data points
#Here we are splitting the data set into two equal halves where 1st on is for training and another one is for testing purpose
L_train, L_test, M_train, M_test = train_test_split(L,M,test_size = 0.5, random_state = 0, shuffle = False)
print(L_train)
print(M_train)
neighbor = KNeighborsClassifier(n_neighbors = 3)
neighbor.fit(L_train,M_train)
M_pred = neighbor.predict(L_test)
print(M_pred) #This prints the predictions in the form of array
print(type(M_pred))

[[1 0]
 [2 0]
 [3 0]
 [6 0]]
[0 0 1 1]
[1 1 1 1]
<class 'numpy.ndarray'>


In [9]:
from sklearn.metrics import confusion_matrix#Here we are importing confusion matrix from sklearn package
confusion_matrix(M_test,M_pred)#Here we are comparing predicted class labels with test class ones

array([[0, 3],
       [0, 1]])

In [ ]:
#And the rest like Accuracy,sensitivity,specificity,are caluculated and written clearly on the word document

In [18]:
print(lbs)

[150, 155, 145, 148]


In [19]:
kgs

[]

In [5]:
lbs

[150, 155, 145, 148]

In [8]:
kgs

[]

In [ ]:
23


In [ ]:
2324

In [ ]:
41243
